<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VRKRISH-PC" name="Test" tests="3" failures="1" timestamp="20 Feb 2022 16:44:00 GMT" time="14.259" errors="0">
  <testcase name="test1" time="4.541" classname="firsttest.Testing">
    <failure type="java.lang.AssertionError" message="expected [2] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [0]
	at firsttest.Testing.test1(Testing.java:40)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.002" classname="firsttest.Testing"/>
  <testcase name="test3" time="0.002" classname="firsttest.A"/>
</testsuite> <!-- Test -->
