<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="14259" started-at="2022-02-20T16:43:46Z" finished-at="2022-02-20T16:44:00Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="14259" started-at="2022-02-20T16:43:46Z" finished-at="2022-02-20T16:44:00Z">
      <class name="firsttest.Testing">
        <test-method status="PASS" signature="openbrowser()[pri:0, instance:firsttest.Testing@1604f19]" name="openbrowser" is-config="true" duration-ms="9675" started-at="2022-02-20T22:13:46Z" finished-at="2022-02-20T22:13:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openbrowser -->
        <test-method status="PASS" signature="tes()[pri:0, instance:firsttest.Testing@1604f19]" name="tes" is-config="true" duration-ms="1" started-at="2022-02-20T22:13:56Z" finished-at="2022-02-20T22:13:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tes -->
        <test-method status="FAIL" signature="test1()[pri:0, instance:firsttest.Testing@1604f19]" name="test1" duration-ms="4541" started-at="2022-02-20T22:13:56Z" finished-at="2022-02-20T22:14:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at firsttest.Testing.test1(Testing.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="close()[pri:0, instance:firsttest.Testing@1604f19]" name="close" is-config="true" duration-ms="1" started-at="2022-02-20T22:14:00Z" finished-at="2022-02-20T22:14:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method status="PASS" signature="test2()[pri:0, instance:firsttest.Testing@1604f19]" name="test2" duration-ms="2" started-at="2022-02-20T22:14:00Z" finished-at="2022-02-20T22:14:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="tes()[pri:0, instance:firsttest.Testing@1604f19]" name="tes" is-config="true" duration-ms="0" started-at="2022-02-20T22:14:00Z" finished-at="2022-02-20T22:14:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tes -->
        <test-method status="PASS" signature="close1()[pri:0, instance:firsttest.Testing@1604f19]" name="close1" is-config="true" duration-ms="1" started-at="2022-02-20T22:14:00Z" finished-at="2022-02-20T22:14:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close1 -->
        <test-method status="PASS" signature="close()[pri:0, instance:firsttest.Testing@1604f19]" name="close" is-config="true" duration-ms="0" started-at="2022-02-20T22:14:00Z" finished-at="2022-02-20T22:14:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- firsttest.Testing -->
      <class name="firsttest.A">
        <test-method status="PASS" signature="test3()[pri:0, instance:firsttest.A@23a2f9]" name="test3" duration-ms="2" started-at="2022-02-20T22:14:00Z" finished-at="2022-02-20T22:14:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
      </class> <!-- firsttest.A -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
